title: HiveSense Dashboard

views:
  - title: Hives
    path: hives
    icon: mdi:bee

    cards:
      - type: custom:auto-entities
        card:
          type: entities
          title: 🐝 Active Beehives
        filter:
          include:
            - domain: sensor
              attributes:
                device_class: temperature
        sort:
          method: name
        card_param: entities
        unique: true
        options:
          type: custom:fold-entity-row
          head:
            type: section
            label: >
              {{ state_attr(entity_id, 'device_name') if state_attr(entity_id, 'device_name') else name }}
          entities:
            - type: custom:auto-entities
              card:
                type: grid
                columns: 2
                square: false
              filter:
                include:
                  - device: "{{ device_id }}"
                    domain: sensor
              card_param: cards
              options:
                type: gauge
                min: 0
                max: 50
                severity:
                  green: 30
                  yellow: 35
                  red: 40

            - type: custom:auto-entities
              card:
                type: history-graph
                hours_to_show: 24
                refresh_interval: 60
              filter:
                include:
                  - device: "{{ device_id }}"
                    domain: sensor
              card_param: entities
