title: HiveSense Dashboard
views:
  - title: Hives
    path: hives
    icon: mdi:bee
    badges: []
    cards:
      - type: custom:auto-entities
        card:
          type: vertical-stack
          title: All Beehives
        filter:
          include:
            - entity_id: sensor.*broodbox_temperature
            - entity_id: sensor.*humidity
            - entity_id: sensor.*air_temperature
            - entity_id: sensor.*pressure
        sort:
          method: name
        card_param: cards
        # Template for each entity
        options:
          type: vertical-stack
          cards:
            - type: gauge
              entity: "{{ entity_id }}"
              name: "{{ name }}"
              min: 0
              max: 50
              severity:
                green: 30
                yellow: 35
                red: 40
            - type: history-graph
              title: "{{ name }} History"
              entities:
                - "{{ entity_id }}"
              hours_to_show: 24
              refresh_interval: 60
